Task 2
ssinelnik/TestGuru pull request #2
Opened 2024-05-30 10:40 UTC by ssinelnik

### Задание 2

**1. Создайте Rails-модели с нужными атрибутами для следующих сущностей:**
- Тест
- Вопрос
- Ответ
- Пользователь
- Категория

2. **С помощью механизма миграций, добавьте ограничения целостности на уровне БД в соответствующих таблицах для необходимых атрибутов так, чтобы они не могли содержать значение NULL**

3. **С помощью механизма миграций добавьте значения по умолчанию:**
- Для уровня Теста
- Для атрибута correct у Ответа

2024-05-30 16:15 UTC, VidgarVii requested changes

2024-05-30 16:15 UTC, VidgarVii commented on app/models/question.rb
> +  belongs_to :test
ассоциации позже будут в курсе
пока лучше убери их из моделей, чтобы они не отвлекали. Тем более они объявлены не верно.
Нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

2024-05-30 16:15 UTC, VidgarVii requested changes

2024-05-30 16:15 UTC, VidgarVii commented on db/migrate/20240530101559_create_tests.rb
> +      t.references :author, null: false, foreign_key: true
Эта миграция не работает.

2024-06-01 07:02 UTC, VidgarVii requested changes

2024-06-01 07:02 UTC, VidgarVii commented on db/migrate/20240531185115_create_questions.rb
> +      t.references :answer, null: false, foreign_key: true
вопрос не может принадлежать ответу. Скорее на оборот

2024-06-01 07:02 UTC, VidgarVii commented on db/migrate/20240531185541_create_tests.rb
> +      t.references :question, null: false, foreign_key: true
Тест не может принадлежать вопросу
Пересмотри урок по SQL. Тему foreign key

2024-06-01 07:02 UTC, VidgarVii commented on db/migrate/20240531185541_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
При проектировании таблиц надо учитывать смысловую нагрузку.
Лучше если поле в таблице будет называться author_id.
Так как по логике нам надо создать связь теста с юзером как автор теста
т.е. должно получиться
t.references :author... 
Но учти чтоб внешний ключ смотрел на таблицу юзеров
для foreign_key нужно использовать опцию to_table

2024-06-01 08:45 UTC, ssinelnik commented on app/models/bin/rail.rb
> +class Bin::Rail < ApplicationRecord
Прошу прощения, это был мисклик и команда продублировалась при вставке в терминал

2024-06-02 08:52 UTC, VidgarVii requested changes

2024-06-02 08:52 UTC, VidgarVii commented on db/migrate/20240601161136_create_users.rb
> +      t.references :test_id, null: false, foreign_key: { to_table: :tests }
1 юзер ни кому не принадлежит. Везде связи объявлены не верно
Должно быть 
Тест принадлежит Категории и Автору
Вопрос принадлежит тесту 
Ответ принадлежит вопросу

2 Метод references использован не верн. Он принимает название ассоциации, а не колонку. Т.е. должно было быть так 
```
  t.references :test, ....
```

2024-06-07 14:19 UTC, merged